// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES


/**
 * @brief Construct a new OI::OI object
 * 
 * 1. Initialize all push buttons (on push button panel)
 * 2. Initialize buttons for rotate commands
 * 3. Initialize buttons on driver joystick for hatch drop, vision lock, exposure toggle,
 *    intake/outtake, and raising robot
 */
OI::OI() {
    // Process operator interface input here.
//    pushbuttonPanel.reset(new frc::Joystick(2));

   driverJoystick.reset(new frc::Joystick(0));

   // if (Robot::IsTankDrive()) {
   //     driverJoystickRight.reset(new frc::Joystick(3));
   // }

   operatorJoystick.reset(new frc::XboxController(1));

   // driver joystick button setups
	joystickDriverButtonVisionLock.reset(new frc::JoystickButton(driverJoystick.get(), 2));

// override buttons for when we lose xbox controller mid match. Driver can get full control
// of robot. 2 new commands created for these buttons. 

//operator xbox controller gets full control of the robot when the driver stick goes out. 
// 4 specific commands calling velocity arcade method in drivetrain. 
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

/**
 * @brief Get the left driver joystick pointer
 * 
 * @return std::shared_ptr<frc::Joystick> 
 */
std::shared_ptr<frc::Joystick> OI::getDriverJoystick() {
   return driverJoystick;
}

/**
 * @brief Get the push button panel pointer
 * 
 * @return std::shared_ptr<frc::Joystick> 
 */
std::shared_ptr<frc::Joystick> OI::getPushbuttonPanel() {
   return pushbuttonPanel;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

/**
 * @brief Get the operator joystick pointer
 * 
 * @return std::shared_ptr<frc::Joystick> 
 */
std::shared_ptr<frc::XboxController> OI::getOperatorJoystick() {
   return operatorJoystick;
}

/**
 * @brief Get the right driver joystick pointer
 * 
 * @return std::shared_ptr<frc::Joystick> 
 */
std::shared_ptr<frc::Joystick> OI::getDriverJoystickRight() {
   return driverJoystickRight;
}
